## Mail storage
mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir
mail_privileged_group = vmail

namespace inbox {
  inbox = yes
  type  = private

  mailbox Drafts {
    auto        = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto        = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto        = subscribe
    special_use = \Trash
  }
  mailbox Junk {
    auto        = subscribe
    special_use = \Junk
  }
  mailbox Archive {
    auto        = subscribe
    special_use = \Archive
  }
}
