development:
  address: imap
  port: 587
  domain: localhost.localdomain.jp
  user_name:
  password:
  authentication:

test:
  address: imap
  port: 587
  domain: localhost.localdomain.jp
  user_name:
  password:
  authentication:

production:
  address: imap
  port: 587
  domain: localhost.localdomain.jp
  user_name:
  password:
  authentication:
