[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:postfix]
command=/usr/sbin/postfix -c /etc/postfix start-fg
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
